# Generated by Django 4.0.3 on 2022-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(max_length=256)),
                ('order_no', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('client_phone', models.IntegerField()),
                ('client_address', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=256)),
                ('delivery_status', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('delivery_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('confirmed', models.CharField(max_length=256)),
            ],
        ),
    ]
