# Generated by Django 4.0.3 on 2022-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.BigIntegerField(),
        ),
    ]
